name: "Elmo's World"
favicon: null
layout_spectrum: 0.49896
typography_spectrum: 0.5744258179329336
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#f2f2f4'
    - '#cd140c'
    - '#e8ad32'
    - '#393939'
  brandStrength: 0.8423893020953983
  lightness: 0.21009698463603854
  saturation: 0.028389266692101955
  rhythmicContrast: 0.7735101289581507
purpose: []
